### ISSUE TITLE
Icons not showing on Tor Browser

### ISSUE THREAD

**Issue by Vitali64GitHub** [Sosasees/tenacity-webpage#5]
The icons aren't showing up

**Comment by Vitali64GitHub** [comment]
You should probably use png icons instead of SVG

**Comment by Sosasees** [comment]
I think replacing the icons completely with the PNG format is not a good idea.

There's a good reason why I used the SVG file format in the first place:
So that the images will stay sharp on higher zoom levels and on screens with higher pixel densities, while having a smaller filesize.

To have the PNG images stay sharp, I could make them High-Resolution, but their filesize would be absurdly large for the use-case. SVGs with normal-resolution PNG fallbacks is a much better option because of the reasonably small file size.
